export const gameDayPlayers = [
  {
    id: 1,
    name: "Alex Martinez",
    number: 1,
    shots: 0,
    goals: 0,
    assists: 0,
    timeIn: 1500,
    timeInCurrent: null,
    timeOut: null,
    timeOutRecent: null,
    inGoalTime: 1500,
    inGoalTimeCurrent: 1500,
    fouls: 0,
    yellowCards: 0,
    redCards: 0,
    saves: 8,
    goalsAgainst: 1,
    gameStatus: "goalkeeper",
    fieldStatus: "onFieldGk",
  },
  {
    id: 2,
    name: "Sarah Johnson",
    number: 5,
    shots: 3,
    goals: 1,
    assists: 2,
    timeIn: 1500,
    timeInCurrent: 1500,
    timeOut: null,
    timeOutRecent: null,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 1,
    yellowCards: 0,
    redCards: 0,
    saves: 0,
    goalsAgainst: 0,
    gameStatus: "starter",
    fieldStatus: "onField",
  },
  {
    id: 3,
    name: "Michael Chen",
    number: 7,
    shots: 5,
    goals: 2,
    assists: 1,
    timeIn: 1500,
    timeInCurrent: 1500,
    timeOut: null,
    timeOutRecent: null,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 2,
    yellowCards: 1,
    redCards: 0,
    saves: 0,
    goalsAgainst: 0,
    gameStatus: "starter",
    fieldStatus: "onField",
  },
  {
    id: 4,
    name: "Emily Davis",
    number: 10,
    shots: 4,
    goals: 1,
    assists: 3,
    timeIn: 1500,
    timeInCurrent: 1500,
    timeOut: null,
    timeOutRecent: null,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 0,
    yellowCards: 0,
    redCards: 0,
    saves: 0,
    goalsAgainst: 0,
    gameStatus: "starter",
    fieldStatus: "onField",
  },
  {
    id: 5,
    name: "David Rodriguez",
    number: 3,
    shots: 2,
    goals: 0,
    assists: 1,
    timeIn: 1500,
    timeInCurrent: 1500,
    timeOut: null,
    timeOutRecent: null,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 3,
    yellowCards: 1,
    redCards: 0,
    saves: 0,
    goalsAgainst: 0,
    gameStatus: "starter",
    fieldStatus: "onField",
  },
  {
    id: 6,
    name: "Jessica Lee",
    number: 8,
    shots: 1,
    goals: 0,
    assists: 2,
    timeIn: 1200,
    timeInCurrent: 300,
    timeOut: 300,
    timeOutRecent: 300,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 1,
    yellowCards: 0,
    redCards: 0,
    saves: 0,
    goalsAgainst: 0,
    gameStatus: "starter",
    fieldStatus: "subbingOut",
  },
  {
    id: 7,
    name: "Robert Taylor",
    number: 12,
    shots: 2,
    goals: 1,
    assists: 0,
    timeIn: 900,
    timeInCurrent: 900,
    timeOut: null,
    timeOutRecent: null,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 0,
    yellowCards: 0,
    redCards: 0,
    saves: 0,
    goalsAgainst: 0,
    gameStatus: "starter",
    fieldStatus: "onField",
  },
  {
    id: 8,
    name: "Amanda Wilson",
    number: 14,
    shots: 0,
    goals: 0,
    assists: 1,
    timeIn: 600,
    timeInCurrent: null,
    timeOut: 900,
    timeOutRecent: 300,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 0,
    yellowCards: 0,
    redCards: 0,
    saves: 0,
    goalsAgainst: 0,
    gameStatus: "starter",
    fieldStatus: "onField",
  },
  {
    id: 9,
    name: "Christopher Brown",
    number: 16,
    shots: 1,
    goals: 0,
    assists: 0,
    timeIn: 480,
    timeInCurrent: null,
    timeOut: 1020,
    timeOutRecent: 720,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 1,
    yellowCards: 0,
    redCards: 0,
    saves: 0,
    goalsAgainst: 0,
    gameStatus: "bench",
    fieldStatus: "onBench",
  },
  {
    id: 10,
    name: "Lauren Martinez",
    number: 18,
    shots: 0,
    goals: 0,
    assists: 0,
    timeIn: 0,
    timeInCurrent: null,
    timeOut: null,
    timeOutRecent: null,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 0,
    yellowCards: 0,
    redCards: 0,
    saves: 0,
    goalsAgainst: 0,
    gameStatus: "bench",
    fieldStatus: "subbingIn",
  },
  {
    id: 11,
    name: "Daniel Garcia",
    number: 20,
    shots: 3,
    goals: 1,
    assists: 1,
    timeIn: 720,
    timeInCurrent: null,
    timeOut: 780,
    timeOutRecent: 480,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 2,
    yellowCards: 1,
    redCards: 0,
    saves: 0,
    goalsAgainst: 0,
    gameStatus: "starter",
    fieldStatus: "onField",
  },
  {
    id: 12,
    name: "Olivia Anderson",
    number: 22,
    shots: 0,
    goals: 0,
    assists: 0,
    timeIn: 0,
    timeInCurrent: null,
    timeOut: null,
    timeOutRecent: null,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 0,
    yellowCards: 0,
    redCards: 0,
    saves: 0,
    goalsAgainst: 0,
    gameStatus: "bench",
    fieldStatus: "onBench",
  },
  {
    id: 13,
    name: "Matthew Thompson",
    number: 24,
    shots: 0,
    goals: 0,
    assists: 0,
    timeIn: 0,
    timeInCurrent: null,
    timeOut: null,
    timeOutRecent: null,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 0,
    yellowCards: 0,
    redCards: 0,
    saves: 0,
    goalsAgainst: 0,
    gameStatus: "starter",
    fieldStatus: "onField",
  },
  {
    id: 14,
    name: "Sophia White",
    number: 26,
    shots: 0,
    goals: 0,
    assists: 0,
    timeIn: 0,
    timeInCurrent: null,
    timeOut: null,
    timeOutRecent: null,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 0,
    yellowCards: 0,
    redCards: 0,
    saves: 0,
    goalsAgainst: 0,
    gameStatus: "starter",
    fieldStatus: "onField",
  },
  {
    id: 15,
    name: "James Harris",
    number: 28,
    shots: 0,
    goals: 0,
    assists: 0,
    timeIn: 0,
    timeInCurrent: null,
    timeOut: null,
    timeOutRecent: null,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 0,
    yellowCards: 0,
    redCards: 0,
    saves: 0,
    goalsAgainst: 0,
    gameStatus: "available",
    fieldStatus: null,
  },
  {
    id: 16,
    name: "Isabella Clark",
    number: 30,
    shots: 0,
    goals: 0,
    assists: 0,
    timeIn: 0,
    timeInCurrent: null,
    timeOut: null,
    timeOutRecent: null,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 0,
    yellowCards: 0,
    redCards: 0,
    saves: 0,
    goalsAgainst: 0,
    gameStatus: "unavailable",
    fieldStatus: null,
  },
  {
    id: 17,
    name: "Ethan Lewis",
    number: 32,
    shots: 0,
    goals: 0,
    assists: 0,
    timeIn: 0,
    timeInCurrent: null,
    timeOut: null,
    timeOutRecent: null,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 0,
    yellowCards: 0,
    redCards: 0,
    saves: 2,
    goalsAgainst: 0,
    gameStatus: "injured",
    fieldStatus: null,
  },
  {
    id: 18,
    name: "Mia Walker",
    number: 34,
    shots: 0,
    goals: 0,
    assists: 0,
    timeIn: 0,
    timeInCurrent: null,
    timeOut: null,
    timeOutRecent: null,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 0,
    yellowCards: 0,
    redCards: 0,
    saves: 0,
    goalsAgainst: 0,
    gameStatus: "unavailable",
    fieldStatus: null,
  },
];

// mockGame.js
export const mockGame = {
  id: 1,
  homeTeam: "Thunder FC",
  awayTeam: "Lightning United",
  homeScore: 3,
  awayScore: 1,
  currentPeriod: 2,
  totalPeriods: 2,
  periodLength: 1800, // 30 minutes in seconds
  currentTime: 1500, // 25 minutes into period 2
  isRunning: true,
  periods: [
    {
      number: 1,
      startTime: 0,
      endTime: 1800,
      completed: true,
    },
    {
      number: 2,
      startTime: 0,
      endTime: 1800,
      completed: false,
    },
  ],
};
