export const gameDayPlayers = [
  {
    id: 1,
    name: "Alex Martinez",
    number: 1,
    shots: 0,
    goals: 0,
    assists: 0,

    timeInCurrent: null,
    timeOut: null,
    timeOutRecent: null,
    inGoalTime: 1500,
    inGoalTimeCurrent: 1500,
    fouls: 0,
    yellowCards: 0,
    redCards: 0,
    saves: 8,
    goalsAgainst: 1,
    gameStatus: "goalkeeper",
    fieldStatus: "onFieldGk",
  },
  {
    id: 2,
    name: "Sarah Johnson",
    number: 5,
    shots: 3,
    goals: 1,
    assists: 2,

    timeInCurrent: 1500,
    timeOut: null,
    timeOutRecent: null,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 1,
    yellowCards: 0,
    redCards: 0,
    saves: 0,
    goalsAgainst: 0,
    gameStatus: "starter",
    fieldStatus: "onField",
  },
  {
    id: 3,
    name: "Michael Chen",
    number: 7,
    shots: 5,
    goals: 2,
    assists: 1,

    timeInCurrent: 1500,
    timeOut: null,
    timeOutRecent: null,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 2,
    yellowCards: 1,
    redCards: 0,
    saves: 0,
    goalsAgainst: 0,
    gameStatus: "starter",
    fieldStatus: "onField",
  },
  {
    id: 4,
    name: "Emily Davis",
    number: 10,
    shots: 4,
    goals: 1,
    assists: 3,

    timeInCurrent: 1500,
    timeOut: null,
    timeOutRecent: null,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 0,
    yellowCards: 0,
    redCards: 0,
    saves: 0,
    goalsAgainst: 0,
    gameStatus: "starter",
    fieldStatus: "onField",
  },
  {
    id: 5,
    name: "David Rodriguez",
    number: 3,
    shots: 2,
    goals: 0,
    assists: 1,

    timeInCurrent: 1500,
    timeOut: null,
    timeOutRecent: null,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 3,
    yellowCards: 1,
    redCards: 0,
    saves: 0,
    goalsAgainst: 0,
    gameStatus: "starter",
    fieldStatus: "onField",
  },
  {
    id: 6,
    name: "Jessica Lee",
    number: 8,
    shots: 1,
    goals: 0,
    assists: 2,

    timeInCurrent: 300,
    timeOut: 300,
    timeOutRecent: 300,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 1,
    yellowCards: 0,
    redCards: 0,
    saves: 0,
    goalsAgainst: 0,
    gameStatus: "starter",
    fieldStatus: "subbingOut",
  },
  {
    id: 7,
    name: "Robert Taylor",
    number: 12,
    shots: 2,
    goals: 1,
    assists: 0,

    timeInCurrent: 900,
    timeOut: null,
    timeOutRecent: null,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 0,
    yellowCards: 0,
    redCards: 0,
    saves: 0,
    goalsAgainst: 0,
    gameStatus: "starter",
    fieldStatus: "onField",
  },
  {
    id: 8,
    name: "Amanda Wilson",
    number: 14,
    shots: 0,
    goals: 0,
    assists: 1,

    timeInCurrent: null,
    timeOut: 900,
    timeOutRecent: 300,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 0,
    yellowCards: 0,
    redCards: 0,
    saves: 0,
    goalsAgainst: 0,
    gameStatus: "starter",
    fieldStatus: "onField",
  },
  {
    id: 9,
    name: "Christopher Brown",
    number: 16,
    shots: 1,
    goals: 0,
    assists: 0,

    timeInCurrent: null,
    timeOut: 1020,
    timeOutRecent: 720,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 1,
    yellowCards: 0,
    redCards: 0,
    saves: 0,
    goalsAgainst: 0,
    gameStatus: "bench",
    fieldStatus: "onBench",
  },
  {
    id: 10,
    name: "Lauren Martinez",
    number: 18,
    shots: 0,
    goals: 0,
    assists: 0,

    timeInCurrent: null,
    timeOut: null,
    timeOutRecent: null,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 0,
    yellowCards: 0,
    redCards: 0,
    saves: 0,
    goalsAgainst: 0,
    gameStatus: "bench",
    fieldStatus: "subbingIn",
  },
  {
    id: 11,
    name: "Daniel Garcia",
    number: 20,
    shots: 3,
    goals: 1,
    assists: 1,

    timeInCurrent: null,
    timeOut: 780,
    timeOutRecent: 480,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 2,
    yellowCards: 1,
    redCards: 0,
    saves: 0,
    goalsAgainst: 0,
    gameStatus: "starter",
    fieldStatus: "onField",
  },
  {
    id: 12,
    name: "Olivia Anderson",
    number: 22,
    shots: 0,
    goals: 0,
    assists: 0,

    timeInCurrent: null,
    timeOut: null,
    timeOutRecent: null,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 0,
    yellowCards: 0,
    redCards: 0,
    saves: 0,
    goalsAgainst: 0,
    gameStatus: "bench",
    fieldStatus: "onBench",
  },
  {
    id: 13,
    name: "Matthew Thompson",
    number: 24,
    shots: 0,
    goals: 0,
    assists: 0,

    timeInCurrent: null,
    timeOut: null,
    timeOutRecent: null,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 0,
    yellowCards: 0,
    redCards: 0,
    saves: 0,
    goalsAgainst: 0,
    gameStatus: "starter",
    fieldStatus: "onField",
  },
  {
    id: 14,
    name: "Sophia White",
    number: 26,
    shots: 0,
    goals: 0,
    assists: 0,

    timeInCurrent: null,
    timeOut: null,
    timeOutRecent: null,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 0,
    yellowCards: 0,
    redCards: 0,
    saves: 0,
    goalsAgainst: 0,
    gameStatus: "starter",
    fieldStatus: "onField",
  },
  {
    id: 15,
    name: "James Harris",
    number: 28,
    shots: 0,
    goals: 0,
    assists: 0,

    timeInCurrent: null,
    timeOut: null,
    timeOutRecent: null,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 0,
    yellowCards: 0,
    redCards: 0,
    saves: 0,
    goalsAgainst: 0,
    gameStatus: "available",
    fieldStatus: null,
  },
  {
    id: 16,
    name: "Isabella Clark",
    number: 30,
    shots: 0,
    goals: 0,
    assists: 0,

    timeInCurrent: null,
    timeOut: null,
    timeOutRecent: null,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 0,
    yellowCards: 0,
    redCards: 0,
    saves: 0,
    goalsAgainst: 0,
    gameStatus: "unavailable",
    fieldStatus: null,
  },
  {
    id: 17,
    name: "Ethan Lewis",
    number: 32,
    shots: 0,
    goals: 0,
    assists: 0,

    timeInCurrent: null,
    timeOut: null,
    timeOutRecent: null,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 0,
    yellowCards: 0,
    redCards: 0,
    saves: 2,
    goalsAgainst: 0,
    gameStatus: "injured",
    fieldStatus: null,
  },
  {
    id: 18,
    name: "Mia Walker",
    number: 34,
    shots: 0,
    goals: 0,
    assists: 0,

    timeInCurrent: null,
    timeOut: null,
    timeOutRecent: null,
    inGoalTime: 0,
    inGoalTimeCurrent: null,
    fouls: 0,
    yellowCards: 0,
    redCards: 0,
    saves: 0,
    goalsAgainst: 0,
    gameStatus: "unavailable",
    fieldStatus: null,
  },
];

// mockGame.js
export const mockGame = {
  id: 1,
  homeTeam: "Thunder FC",
  awayTeam: "Lightning United",
  homeScore: 3,
  awayScore: 1,
  periodLength: 1800, // 30 minutes in seconds
  isCountdown: false,
  periods: [],
};

// Mock data - replace with your API calls
export const mockClubs = [
  {
    id: 1,
    name: "Brentwood High School",
    location_name: "Brentwood, TN",
    founded_year: 1982,
    club_type: "High School",
  },
  {
    id: 2,
    name: "Franklin High School",
    location_name: "Franklin, TN",
    founded_year: 1952,
    club_type: "High School",
  },
  {
    id: 3,
    name: "Nashville United SC",
    location_name: "Nashville, TN",
    founded_year: 2002,
    club_type: "Club",
  },
];

export const mockSeasons = [
  {
    id: 1,
    name: "2024-25",
    start_date: "2024-08-01",
    end_date: "2025-05-31",
    is_active: true,
  },
  {
    id: 2,
    name: "2023-24",
    start_date: "2023-08-01",
    end_date: "2024-05-31",
    is_active: false,
  },
];

export const mockTeams = [
  {
    id: 1,
    name: "Varsity Boys",
    club_id: 1,
    club_name: "Brentwood High School",
    team_type: "Varsity",
    gender: "male",
    age_group: null,
    roster_count: 18,
    is_active: true,
  },
  {
    id: 2,
    name: "JV Boys",
    club_id: 1,
    club_name: "Brentwood High School",
    team_type: "JV",
    gender: "male",
    age_group: null,
    roster_count: 16,
    is_active: true,
  },
  {
    id: 3,
    name: "Varsity Girls",
    club_id: 2,
    club_name: "Franklin High School",
    team_type: "Varsity",
    gender: "female",
    age_group: null,
    roster_count: 20,
    is_active: true,
  },
  {
    id: 4,
    name: "U17 Boys NPL",
    club_id: 3,
    club_name: "Nashville United SC",
    team_type: "Club",
    gender: "male",
    age_group: "U17",
    roster_count: 22,
    is_active: true,
  },
];
